name: Deploy to EC2

on:
  push:
    branches:
      - main  # Monitor the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Updated to v4

    - name: Set up Python
      uses: actions/setup-python@v5  # Updated to v5
      with:
        python-version: '3.x'  # Specify the Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python -m unittest discover -s .

    - name: Deploy to EC2
      env:
        EC2_HOST: "35.154.243.86"  # Your public IP
        EC2_USER: ${{ secrets.EC2_USER }}
        EC2_KEY: ${{ secrets.EC2_KEY }}
      run: |
        scp -o StrictHostKeyChecking=no -i "$EC2_KEY" -r * $EC2_USER@$EC2_HOST:~/simple-webapp-flask-master/simple-webapp-flask-master
        ssh -o StrictHostKeyChecking=no -i "$EC2_KEY" $EC2_USER@$EC2_HOST << 'EOF'
          cd ~/simple-webapp-flask-master/simple-webapp-flask-master
          pip3 install -r requirements.txt
          pkill -f "python3 app.py" || true  # Stop any existing app instances
          nohup python3 app.py &  # Run app in background
        EOF
